pipeline {
    agent any

    environment {
        DOCKER_IMAGE  = "karthik713/static-website"
        GIT_REPO_NAME = "python-flask-app"
        GIT_USER_NAME = "karthikpillai713"
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {

        stage('Checkout') {
            steps {
              sh 'echo "passed"'
                // git branch: 'main', url: 'https://github.com/Doom710/python-flask-app'
                echo 'Source code already checked out by Jenkins SCM'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonarscanner'

                    withSonarQubeEnv('sonarqube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=flask-gitops-app \
                            -Dsonar.projectName='Flask GitOps App' \
                            -Dsonar.sources=python-flask-app/app/ \
                            -Dsonar.language=py \
                            -Dsonar.python.version=3.11 \
                            -Dsonar.sourceEncoding=UTF-8
                        """
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    sh '''
                        docker build \
                        -t ${DOCKER_IMAGE}:${BUILD_NUMBER} \
                        python-flask-app/
                    '''

                    withCredentials([
                        usernamePassword(
                            credentialsId: 'docker-cred',
                            usernameVariable: 'DOCKER_USERNAME',
                            passwordVariable: 'DOCKER_PASSWORD'
                        )
                    ]) {
                        sh '''
                            echo "$DOCKER_PASSWORD" | docker login \
                                -u "$DOCKER_USERNAME" \
                                --password-stdin

                            docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}

                            docker tag \
                                ${DOCKER_IMAGE}:${BUILD_NUMBER} \
                                ${DOCKER_IMAGE}:latest

                            docker push ${DOCKER_IMAGE}:latest

                            docker logout
                        '''
                    }
                }
            }
        }

        stage('Update Deployment File') {
            steps {
                withCredentials([
                    string(
                        credentialsId: 'github',
                        variable: 'GITHUB_TOKEN'
                    )
                ]) {
                    sh '''
                        git config user.email "karthikpillai713@gmail.com"
                        git config user.name "${GIT_USER_NAME}"

                        sed -i "s|image: .*|image: ${DOCKER_IMAGE}:${BUILD_NUMBER}|g" \
                            python-flask-app/k8s/deployment.yaml

                        git add python-flask-app/k8s/deployment.yaml

                        git commit \
                            -m "Update flask app image tag to ${BUILD_NUMBER} [skip ci]" \
                            || echo "No changes to commit"

                        git push \
                            "https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git" \
                            HEAD:main
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
